name: Docker Image CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Initiate Git submodules
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rpsbot:$(date +%s)
